name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v3.1.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Restore cache
      uses: actions/cache@v3.2.4
      with:
        path: yarn.lock
        key: ${{ runner.os }}--{{ hashFiles('yarn.lock') }}
    - name: Install dependencies
      run: |
        npm i -g yarn
        yarn install --immutable
    - name: Run unittests
      run: |
        yarn test
    - name: Run integration tests
      run: |
        yarn test:e2e
